# Generated by Django 2.2.7 on 2019-11-21 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='poll',
            name='next_poll',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='slug',
        ),
        migrations.AddField(
            model_name='poll',
            name='presentation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.Presentation'),
        ),
    ]
