# Generated by Django 2.2.7 on 2019-11-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20191121_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='ended',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='published',
        ),
        migrations.AddField(
            model_name='poll',
            name='live',
            field=models.BooleanField(default=False),
        ),
    ]
